### ISSUE TITLE
Expected conditions logged as error

### ISSUE THREAD

**Issue by renatomariscal** [Wattpad/kube-sqs-autoscaler#11]
Hi,

I see a bunch of these in my logs:
```
level=error msg="Failed scaling down: Min pods reached"
```

Which is an expected situation, right? So why is it logged as error? I believe just `info` would be accurate.

I had issues recently that are real errors, so I would like to configure my metric system to create alerts for any error. But it is not doable while we get errors in regular scenarios.

Thanks!

**Comment by stafot** [comment]
Agree that this should be `info` not `error`

**Comment by renatomariscal** [comment]
https://github.com/Wattpad/kube-sqs-autoscaler/pull/8 seems to fix it

**Comment by stafot** [comment]
@renatomariscal let's pray to merge it. Or use a fork and merge it :)

**Comment by renatomariscal** [comment]
As neither this nor the PR has gotten attention in a year, I am assuming this repo is abandoned, and I will be working permanently from a fork. 🤷‍♂
